[versions]
agp = "8.13.0"
coreTesting = "2.2.0"
fragmentTesting = "1.6.2"
hiltAndroidCompiler = "2.48"
hiltAndroidTestingVersion = "2.48"
jetbrainsKotlinxCoroutinesTest = "1.7.3"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesTest = "1.10.2"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
ksp-version = "2.2.20-2.0.4"
hilt-version = "2.57.2"
rules = "1.5.0"
runnerVersion = "1.5.2"
saveargs-version = "2.7.5"
loggingInterceptor = "5.2.1"
mockk = "1.14.7"
okhttp_version = "5.2.1"
retrofit_version = "3.0.0"
room_version = "2.8.3"
jsoup_version = "1.21.2"
navigation_version = "2.9.5"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
fragmentKtx = "1.8.9"
picasso_version = "2.71828"
material3 = "1.4.0"
simpleXml = "2.7.1"
timber = "5.0.1"
roomCompilerProcessingTesting = "2.8.4"
glide_version = "4.16.0"
espressoContrib = "3.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTesting" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigation_version" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room_version" }
androidx-rules = { module = "androidx.test:rules", version.ref = "rules" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "rules" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-version" }
dagger-hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-version" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp_version" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit_version" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit_version" }
converter-simplexml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "retrofit_version" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx" , version.ref = "navigation_version"}
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx" , version.ref = "navigation_version"}
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup_version"}
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version" }
room-compiler = {module = "androidx.room:room-compiler", version.ref = "room_version" }
glide = {module = "com.github.bumptech.glide:glide", version.ref = "glide_version" }
picasso = {group = "com.squareup.picasso", name = "picasso", version.ref = "picasso_version"}
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
runner = { module = "androidx.test:runner", version.ref = "runnerVersion" }
simple-xml = { module = "org.simpleframework:simple-xml", version.ref = "simpleXml" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-room-compiler-processing-testing = { group = "androidx.room", name = "room-compiler-processing-testing", version.ref = "roomCompilerProcessingTesting" }
androidx-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoContrib" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }
safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "saveargs-version" }

